version: '3.2'
services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

  postgres:
    restart: always
    image: bitnami/postgresql:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: challenge
      POSTGRES_PASSWORD: challenge
      POSTGRES_DB: challenge
    volumes:
      - "/usr/local/postgresql-persistence:/var/lib/postgresql/data"

  api:
    restart: always
    build: ./api
    depends_on:
      - postgres
      - redis
    environment:
      PORT: 3000
      NODE_ENV: production
      # NODE_ENV: develop
      DB_NAME: challenge
      DB_HOSTNAME: postgres
      DB_USERNAME: challenge
      DB_PASSWORD: challenge
      REDIS_URL: redis://cache
      SENTRY_DSN: https://428c8cb67271469aa670d92d4909e8b0@sentry.io/1814043
    ports:
      - "5000:3000"
    volumes:
      - "./api:/api:delegated"

  # dashboard:
  #   restart: always
  #   build: ./dashboard
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - "./dashboard:/dashboard:delegated"
